In [104]:
import numpy as np

In [105]:
# task:1- Array Creation
# Create the following NumPy arrays:
# Q1: An array of integers from 1 to 10

np.arange(1,11)
                                                                                

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
#Q2: An array of five zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [107]:
#Q3:An array of five ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [108]:
#Q4:An array of even numbers from 2 to 20
np.arange(4,41,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40])

In [109]:
# task:2-Array Properties
#Create a 3 × 4 NumPy array and find:
a=np.array([[1,2,3,4],[5,6,7,8],
           [9,10,11,12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [110]:
#Q1:Shape
np.shape(a)

(3, 4)

In [111]:
#Q2:size
np.size(a)

12

In [173]:
#Q3:Number of dimensions
np.ndim(a)


0

In [174]:
#Q4:Data type
type((a))

int

In [175]:
# tash:3-Indexing and Slicing
#Given the array:
a=np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(a)
#Perform the following:

[10 20 30 40 50 60 70 80]


In [176]:
#Q1:Print the first element.
print(a[0:1])

[10]


In [177]:
#Q2:Print the last element
print(a[7])

80


In [178]:
#Q3:Print elements from index 2 to 5.
print(a[2:6])

[30 40 50 60]


In [179]:
#Q4:Print every alternate element
print(a[::2])

[10 30 50 70]


In [180]:
#Q5:Reverse the array.
print(a[-1:-8])

[]


In [181]:
# Task:4-Reshaping Arrays
#Q1:Create an array containing numbers from 1 to 12
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [182]:
#Q2:Convert it into a 3 × 4 matrix.
np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [183]:
#Q3:Convert it into a 2 × 6 matrix
np.reshape(a,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [184]:
#Task:5-Arithmetic Operations
#Create two arrays:
A =np.array([1, 2, 3, 4, 5])
B =np.array([5, 4, 3, 2, 1])
print(A)
print(B)

[1 2 3 4 5]
[5 4 3 2 1]


In [185]:
#Perform:
#Q1:Addition
np.sum([[1,2,3,4,5],[5,4,3,2,1]])

np.int64(30)

In [186]:
#Q2:Subtraction
np.subtract(A,B)

array([-4, -2,  0,  2,  4])

In [187]:
#Q3:Multiplication
np.multiply(A,B)

array([5, 8, 9, 8, 5])

In [188]:
#Q4:Division
np.divide(A,B)

array([0.2, 0.5, 1. , 2. , 5. ])

In [189]:
# Task:6-Statistical Functions
#Create an array:
a=np.array([12, 25, 18, 40, 30, 15])
print(a)

[12 25 18 40 30 15]


In [190]:
#Find:
#Q1:Sum
np.sum(a)

np.int64(140)

In [191]:
#Q2:Mean
np.mean(a)

np.float64(23.333333333333332)

In [192]:
#Q3:Maximum
np.max(a)

np.int64(40)

In [193]:
#Q4:Minimum
np.min(a)

np.int64(12)

In [194]:
#Q5:Standard deviation
np.std(a)

np.float64(9.585869229698938)

In [195]:
# Task:7-Random Arrays
#Create:
#Q1:A random array of 10 integers between 1 and 100
a=np.arange(1,100,10)
print(a)

[ 1 11 21 31 41 51 61 71 81 91]


In [196]:
#Q2:Find the largest value.
np.max(a)

np.int64(91)

In [197]:
#Q3:Find the smallest value.
np.min(a)

np.int64(1)

In [198]:
#Q4:Sort the array.
np.sort(a)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [199]:
# Task:8-Boolean Indexing
#Given the array:
a=np.array([5, 12, 18, 25, 30, 7, 40, 50])
print(a)

[ 5 12 18 25 30  7 40 50]


In [200]:
#Q1:Print elements greater than 20
b=a>20
print(b)

[False False False  True  True False  True  True]


In [201]:
 #Q2:Print even numbers
print(a[a%2==0])

[12 18 30 40 50]


In [202]:
#Q3:Count how many numbers are greater than 15
b=a>15
print(b)

[False False  True  True  True False  True  True]


In [203]:
# Task:9-Matrix Operations
#Q1:Create a 3 × 3 matrix
a=np.arange(2,11)
print(a)

[ 2  3  4  5  6  7  8  9 10]


In [204]:
w=np.reshape(a,(3,3))

In [205]:
#Q2:Find its transpose
np.transpose(a)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [206]:
#Q3:Find the sum of each row
#w[ s :e ,  s:e]
print(w)

print("Row 1 sum:",w[1:0].sum())
print("Row 2 sum:",w[1:2].sum())
print("Row 3 sum:",w[2:3].sum())

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Row 1 sum: 0
Row 2 sum: 18
Row 3 sum: 27


In [207]:
#Q4:Find the sum of each column. 
print("column 1 sum:",w[0:1].sum())
print("column 2 sum:",w[1:2].sum())
print("column 3 sum:",w[2:3].sum())

column 1 sum: 9
column 2 sum: 18
column 3 sum: 27


In [208]:
#Task:10-Mini Practice Problem
#A student scored the following marks:
d=np.array([65, 72, 88, 45, 90, 55, 78, 84, 60, 95])
print(d)

[65 72 88 45 90 55 78 84 60 95]


In [209]:
#Q1:Perform the following:
#Find the highest mark.
np.max(d)

np.int64(95)

In [210]:
#Q2:Find the lowest mark
np.min(d)

np.int64(45)

In [211]:
#Q3:Calculate the average mark
np.average(d)

np.float64(73.2)

In [212]:
#Q4:Display marks greater than 75.
e=d>75 
print(e)

[False False  True False  True False  True  True False  True]


In [213]:
#Q5:Count the number of students who scored above 60.
a=len(d[d>60])
print(a)

7


In [214]:
#Q6:Sort the marks in ascending order.
np.sort(b)

array([False, False, False,  True,  True,  True,  True,  True])